{
 "title": "Gateway Watch",
 "time": { "from": "now-18h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(gatewaywatch_bytes_uploaded, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Direct Upload Success Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaywatch_direct_gateway_checks{status=\"successful\"} / on(type) gatewaywatch_direct_gateway_checks{status=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Deferred Upload Success Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaywatch_deferred_gateway_checks{status=\"successful\"} / on(type) gatewaywatch_deferred_gateway_checks{status=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upload Success Rate per Node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaywatch_uploads{status=\"successful\"} / on(node) gatewaywatch_uploads{status=\"total\"}",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Download Success Rate per Node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gatewaywatch_foreign_downloads{status=\"successful\"} / on(node) gatewaywatch_foreign_downloads{status=\"total\"}",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Direct and Deferred Checks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(gatewaywatch_direct_gateway_checks{status=\"failed\"}[10m])",
     "legendFormat": "direct {{type}}"
    },
    {
     "expr": "increase(gatewaywatch_deferred_gateway_checks{status=\"failed\"}[10m])",
     "legendFormat": "deferred {{type}}"
    }
   ]
  }
 ]
}