{
 "title": "Hive",
 "tags": [ "protocols" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connectivity success rate",
   "type": "gauge",
   "description": "Shows success rate of connection attempts from Hive",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(bee_hive_peer_attempt_count{namespace=~\"$namespace\", instance=~\"$instance\"}-bee_hive_reachable_peers_count{namespace=~\"$namespace\", instance=~\"$instance\"})/bee_hive_peer_attempt_count{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duplicate peer broadcast",
   "type": "stat",
   "description": "Number of duplicate peer broadcasts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_hive_peers_handler_peers_count{namespace=~\"$namespace\", instance=~\"$instance\"} - bee_hive_peer_attempt_count{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer reachability distribution",
   "type": "stat",
   "description": "Peer reachability distribution",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_hive_reachable_peers_count{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reachable peers"
    }
   ]
  },
  {
   "title": "Peer unreachability distribution",
   "type": "stat",
   "description": "Peer unreachability distribution",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_hive_unreachable_peers_count{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} unreachable peers"
    }
   ]
  },
  {
   "title": "Ping time",
   "type": "heatmap",
   "description": "Time taken for ping operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(bee_hive_ping_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Failed ping times",
   "type": "heatmap",
   "description": "Time taken for failed ping operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(bee_hive_fail_ping_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}