{
 "title": "Kademlia",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Depth",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_current_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Light nodes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "bee_lightnode_currently_connected_peers{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connect/Known",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "bee_kademlia_currently_connected_peers{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "connected({{instance}})"
    },
    {
     "expr": "bee_kademlia_currently_known_peers{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "known({{instance}})"
    }
   ]
  },
  {
   "title": "Current Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_kademlia_current_depth{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "depth({{instance}})"
    }
   ]
  },
  {
   "title": "Radius",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bee_kademlia_current_radius{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "radius({{instance}})"
    }
   ]
  },
  {
   "title": "Disconnects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_kademlia_total_inbound_disconnections{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "inbound({{instance}})"
    }
   ]
  },
  {
   "title": "Metrics Flush Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "bee_kademlia_internal_metrics_flush_total_errors{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "metrics_flush_total_errors({{instance}})"
    }
   ]
  },
  {
   "title": "Libp2p blocklisting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_blocklisted_peer_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklist_event({{instance}})"
    }
   ]
  },
  {
   "title": "Metrics Flush Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(bee_kademlia_internal_metrics_flush_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Before Expire Waits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "bee_kademlia_total_before_expire_waits{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "before_expire_waits({{instance}})"
    }
   ]
  },
  {
   "title": "Pick Calls",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "bee_kademlia_pick_calls{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "pick_calls({{instance}})"
    },
    {
     "expr": "bee_kademlia_pick_calls_false{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "pick_calls_false({{instance}})"
    }
   ]
  },
  {
   "title": "Add Addressbook Overlays Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(bee_kademlia_start_add_addressbook_overlays_time_bucket{namespace=~\"$namespace\", instance=~\"$instance\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connection To Bootnodes Attemps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "bee_kademlia_total_bootnodes_connection_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "bootnodes_connection_attempts({{instance}})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "bee_kademlia_total_inbound_connections{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inbound({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_inbound_disconnections{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "inbound_disconnections({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connections{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connection_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound_attempts({{instance}})"
    },
    {
     "expr": "bee_kademlia_total_outbound_connection_failed_attempts{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "outbound_failed_attempts({{instance}})"
    }
   ]
  },
  {
   "title": "Connected Peers Reachability",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bee_kademlia_peers_reachability_status{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{peers_reachability_status}}"
    }
   ]
  }
 ]
}