{
 "title": "P2P",
 "tags": [ "components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(bee_info, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(bee_info{namespace=\"$namespace\"}, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "libp2p created connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bee_libp2p_created_connection_count{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "libp2p handled connection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(bee_libp2p_handled_connection_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "blocklist",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_blocklisted_peer_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklisted_peers({{instance}})"
    },
    {
     "expr": "increase(bee_libp2p_blocklisted_peer_err_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "blocklisted_peers_err({{instance}})"
    }
   ]
  },
  {
   "title": "connect vs. disconnect",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bee_libp2p_disconnect_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "disconnects({{instance}})"
    },
    {
     "expr": "increase(bee_libp2p_created_connection_count{namespace=~\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "connects({{instance}})"
    }
   ]
  }
 ]
}