{
 "title": "Runtime Metrics",
 "description": "Golang Application Runtime Metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{namespace=\"$namespace\"}, instance)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_sys_bytes"
    }
   ]
  },
  {
   "title": "Number of Bytes in Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{namespace=\"$namespace\", instance=~\"$instance\"} - go_memstats_frees_total{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "memstats_inuse_total"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "rate_memstats_mallocs"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", instance=~\"$instance\"}[1m])",
     "legendFormat": "rate_memstats_alloc_bytes"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "gc_duration_s_q{{quantile}}"
    }
   ]
  }
 ]
}